### ISSUE TITLE
Unknown Geometry Type

### ISSUE THREAD

**Issue by pronebird** [DenisCarriere/geojson-rbush#4]
Hi,

I am searching a tree of points, basically I'd like to find the points within the provided bbox.

```
// [nw-lon, nw-lat, se-lon, se-lat]
const bbox = getBbox(projection, zoom);

const match = {
  minX: bbox[0],
  minY: bbox[1],
  maxX: bbox[2],
  maxY: bbox[3],
};

myRbush.search(match);
```

Results in:
> Uncaught Error: Unknown Geometry Type

any pointer why it doesn't work?

Cheers,
Andrej

**Comment by DenisCarriere** [comment]
`geojson-rbush` simply expands [`rbush`](https://github.com/mourner/rbush), maybe try using that library at first to see if you are having the same issues.

**Comment by DenisCarriere** [comment]
At the moment `geojson-rbush` only uses GeoJSON inputs, you're `match` param should either be a GeoJSON Feature, FeatureCollection or BBox.

You can follow the docs here: https://github.com/DenisCarriere/geojson-rbush#search

> Maybe including `rbush`'s `{minX, minY, maxX, maxY}` Object should be included

**Comment by DenisCarriere** [comment]
Closing this issue since the following code should do the trick:

```js
// [nw-lon, nw-lat, se-lon, se-lat]
const bbox = getBbox(projection, zoom);

myRbush.search(bbox);
```

**Comment by pronebird** [comment]
Hi @DenisCarriere,

Thanks! I tried giving it a bbox (i.e `[-4.255047950265636, 4.565931730829302, -4.144793838077576, 4.674651115594198]`) but never got anything back which is weird because I have tons of points there.

**Comment by pronebird** [comment]
I think my issue was related to invalid bbox, or at least now when I tried using it with `rbush` it works fine. Thanks again for all the suggestions!
