### ISSUE TITLE
.load(Feature[]) assumes polygons features

### ISSUE THREAD

**Issue by kpwebb** [DenisCarriere/geojson-rbush#5]
https://github.com/DenisCarriere/geojson-rbush/blob/1373da62e1755519b99d37a53389545513b94f46/index.js#L80

Just ran into this problem using an array of linestring features. the polygon bbox extractor failed silently while trying to extract the bbox from the linestring resulting in a corrupt spatial index.

**Comment by DenisCarriere** [comment]
@kpwebb The valid inputs should be a FeatureCollection of LineString and not an Array of LineString.

I can add the support for it.

https://github.com/DenisCarriere/geojson-rbush#load

**Comment by DenisCarriere** [comment]
I would recommend using Typescript when using this library, that way you don't have any issues when entering the wrong inputs per methods.

TS Definition
https://github.com/DenisCarriere/geojson-rbush/blob/master/index.d.ts#L5

**Comment by DenisCarriere** [comment]
Added support for an Array of Features, that way you don't need to convert it to a FeatureCollection.

CC: @kpwebb 

`geojson-rbush` minor release: `v3.1.0`

```js
const tree = geojsonRbush();
const polys = turf.polygons([
    [[[-78, 41], [-67, 41], [-67, 48], [-78, 48], [-78, 41]]],
    [[[-93, 32], [-83, 32], [-83, 39], [-93, 39], [-93, 32]]]
]);
// Load Feature Collection
tree.load(polys);
tree.all().features.length; // => 2

// Load Array of Features
tree.load(polys.features);
tree.all().features.length; // => 4
```
